// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SmartShop.Payments.Infra.Data.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20260815140000_UniquePaymentPerOrder")]
    partial class UniquePaymentPerOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            PaymentsUniqueOrderModel.Build(modelBuilder);
#pragma warning restore 612, 618
        }
    }

    internal static class PaymentsUniqueOrderModel
    {
        internal static void Build(ModelBuilder modelBuilder)
        {
            PaymentsOutboxModel.Build(modelBuilder);

            modelBuilder.Entity("SmartShop.Payments.Core.Domain.Payments.Payment", b =>
            {
                b.HasIndex("OrderId").IsUnique();
            });
        }
    }
}
