// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SmartShop.Payments.Infra.Data;

#nullable disable

namespace SmartShop.Payments.Infra.Data.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20260815110000_AddOutbox")]
    partial class AddOutbox
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            PaymentsOutboxModel.Build(modelBuilder);
#pragma warning restore 612, 618
        }
    }

    internal static class PaymentsOutboxModel
    {
        internal static void Build(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasDefaultSchema("payments")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartShop.Payments.Core.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
                    b.Property<string>("Method").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<Guid>("OrderId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime?>("PaidAtUtc").HasColumnType("datetime2");
                    b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.HasKey("Id");
                    b.ToTable("Payments", "payments");
                });

            modelBuilder.Entity("SmartShop.Payments.Infra.Data.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<int>("Attempts").HasColumnType("int");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
                    b.Property<string>("LastError").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<DateTime>("OccurredAtUtc").HasColumnType("datetime2");
                    b.Property<string>("Payload").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("ProcessedAtUtc").HasColumnType("datetime2");
                    b.Property<string>("RoutingKey").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Type").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.HasKey("Id");
                    b.HasIndex("ProcessedAtUtc", "CreatedAtUtc");
                    b.ToTable("OutboxMessages", "payments");
                });
        }
    }
}
