// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using SmartShop.Loyalty.Infra.Data;

#nullable disable

namespace SmartShop.Loyalty.Infra.Data.Migrations
{
    [DbContext(typeof(LoyaltyDbContext))]
    [Migration("20260815120000_AddInbox")]
    partial class AddInbox
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            LoyaltyInboxModel.Build(modelBuilder);
#pragma warning restore 612, 618
        }
    }

    internal static class LoyaltyInboxModel
    {
        internal static void Build(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasDefaultSchema("loyalty")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartShop.Loyalty.Core.Domain.Accounts.LoyaltyAccount", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<int>("Balance").HasColumnType("int");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
                    b.Property<Guid>("CustomerId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("CustomerId").IsUnique();
                    b.ToTable("Accounts", "loyalty");
                });

            modelBuilder.Entity("SmartShop.Loyalty.Core.Domain.Accounts.LoyaltyTransaction", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Description").IsRequired().HasMaxLength(250).HasColumnType("nvarchar(250)");
                    b.Property<Guid>("LoyaltyAccountId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("OccurredAtUtc").HasColumnType("datetime2");
                    b.Property<int>("Points").HasColumnType("int");
                    b.Property<Guid>("SourcePaymentId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("LoyaltyAccountId");
                    b.HasIndex("SourcePaymentId").IsUnique();
                    b.ToTable("Transactions", "loyalty");
                });

            modelBuilder.Entity("SmartShop.Loyalty.Infra.Data.Inbox.ProcessedMessage", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("ProcessedAtUtc").HasColumnType("datetime2");
                    b.Property<string>("Type").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.HasKey("Id");
                    b.ToTable("ProcessedMessages", "loyalty");
                });

            modelBuilder.Entity("SmartShop.Loyalty.Core.Domain.Accounts.LoyaltyTransaction", b =>
                {
                    b.HasOne("SmartShop.Loyalty.Core.Domain.Accounts.LoyaltyAccount", null)
                        .WithMany("Transactions")
                        .HasForeignKey("LoyaltyAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartShop.Loyalty.Core.Domain.Accounts.LoyaltyAccount", b =>
                {
                    b.Navigation("Transactions").UsePropertyAccessMode(PropertyAccessMode.Field);
                });
        }
    }
}
