@SmartShop_Loyalty_HostAddress = http://localhost:5221
@CustomerId = 11111111-1111-1111-1111-111111111111

GET {{SmartShop_Loyalty_HostAddress}}/health/ready
Accept: application/json

###

GET {{SmartShop_Loyalty_HostAddress}}/api/loyalty/customers/{{CustomerId}}
Accept: application/json

###

GET {{SmartShop_Loyalty_HostAddress}}/api/loyalty/customers/{{CustomerId}}/transactions
Accept: application/json
